### ISSUE TITLE
Project Improvements? 

### ISSUE THREAD

**Issue by bkudler** [melissamcewen/CurlsBotSite#2]
Hey, I apologize for contacting you through these means, but I didn't know how else to reach out. I really enjoyed your Medium post about sexism and front end development. I see that you have some interesting GitHub projects and I would love to contribute to some. I would really appreciate it if you had some ideas of where to get started. You can contact me at bkudler@gmail.com

thanks for the great article!

**Comment by melissamcewen** [comment]
Hi! Thanks for the kind words! Do you know anything about functional programming? I'd really like to refactor in that direction to make it more modular and testable https://github.com/melissamcewen/curlsbot

**Comment by yejinzai** [comment]
@melissamcewen Hi Melissa! I would also like to reach out to ask if I could become a contributor for curlsbot. Im a curly girl and programmer as well and would like to contribute to the comm! If in case you are interested, I can be reached out at yejinzai@gmail.com. Thanks! :)

**Comment by melissamcewen** [comment]
Awesome sent you an email!

**Comment by melissamcewen** [comment]
@bkudler  sorry I never got back to you, I didn't check my notifications eeek but I've been so busy I haven't been working on it much
